services:
  backend:
    image: lix033/docktor-backend:latest
    group_add:
      - "${DOCKER_GID}"
    volumes:
      - /var/app/logs/doktor:/usr/src/app/logs
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    restart: unless-stopped

  frontend:
    image: lix033/docktor-frontend:latest
    ports:
      - "${FRONTEND_PORT}:3000"
    depends_on:
      - backend
    restart: unless-stopped