services:
  backend:
    image: lix033/docktor-backend:latest
    environment:
      - APPS_ROOT : "/var/app"
    group_add:
      - "${DOCKER_GID}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/app/dokktor-data:/data
    env_file:
      - .env
    restart: unless-stopped

  frontend:
    image: lix033/docktor-frontend:latest
    ports:
      - "${FRONTEND_PORT}:3000"
    depends_on:
      - backend
    restart: unless-stopped